# Generated by Django 6.0.3 on 2026-03-26 08:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0005_blockchainlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farm',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='farm',
            name='farm_name',
        ),
        migrations.AddField(
            model_name='farm',
            name='location',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='farm',
            name='name',
            field=models.CharField(default='My Farm', max_length=100),
        ),
        migrations.AlterField(
            model_name='farm',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='farm_images/'),
        ),
        migrations.AlterField(
            model_name='farm',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='farm',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='farm',
            name='nitrogen',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='farm',
            name='phosphorus',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='farm',
            name='potassium',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='farm',
            name='soil_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='farm',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
