# Generated by Django 6.0.3 on 2026-03-26 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0006_remove_farm_created_at_remove_farm_farm_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farm',
            name='image',
        ),
        migrations.RemoveField(
            model_name='farm',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='farm',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='farm',
            name='soil_type',
        ),
    ]
