# Generated by Django 6.0.3 on 2026-03-26 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0007_remove_farm_image_remove_farm_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='farm_images/'),
        ),
        migrations.AddField(
            model_name='farm',
            name='soil_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
